# LLM配置
llm:
  provider: "openai_deepseek"  # 可选的提供商包括: openai，openai_deepseek，openai_siliconflow，zhipuai
  max_requests: 10  # 最大请求次数
  openai:
    api_key: "your-api-key"
    base_url: "https://api.openai.com/v1"  # 可选，用于自定义API端点
    model: "gpt-4-1106-preview"
    temperature: 0.7
    max_tokens: 8192
  openai_deepseek:
    api_key: "your-api-key" 
    base_url: "https://api.deepseek.com/v1"
    model: "deepseek-chat"
    temperature: 0.7
    max_tokens: 8192
  openai_siliconflow:
    api_key: "your-api-key"
    base_url: "https://api.siliconflow.com/v1"
    model: "gpt-4-1106-preview"
    temperature: 0.7
    max_tokens: 8192
  zhipuai:
    api_key: "your-zhipu-api-key"
    model: "glm-4"  # 智谱AI模型名称
    temperature: 0.7
    max_tokens: 8192

# 输出配置
output:
  default_format: "markdown"  # 可选: markdown, csv, folder
  base_path: "outputs/"
  markdown_template: "templates/markdown_template.md"
  csv_columns: ["title", "url", "summary", "methodology", "results", "timestamp"]

# PDF处理配置
pdf:
  chunk_size: 2000
  chunk_overlap: 200
  max_pages: 50  # 单次处理最大页数

# 提示词配置
prompts:
  file: "config/prompts.yaml"  # 提示词配置文件路径
  default: "summary"
  available:
    - summary
    - methodology
    - results
    - contribution
    - full_analysis

# Agent配置
agent:
  max_iterations: 5
  timeout: 300  # 秒
  memory_window: 10 